export const ProductList = [
  {
    id: 1,
    name: "Sneakers for Sport",
    price: 4000,
    image: "https://example.com/sneakers1.jpg",
    description: "Comfortable and stylish sneakers for sport.",
    quantity: 10,
    transparent_image: true,
    sizable: true,
    colors: ["blue", "red"],
    sizes: ["32", "44", "45"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 3200,
  },
  {
    id: 2,
    name: "Casual Loafers",
    price: 3500,
    image: "https://example.com/loafers1.jpg",
    description: "Elegant casual loafers for everyday wear.",
    quantity: 15,
    transparent_image: false,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["38", "40", "42"],
    discount: 5,
    is_new: false,
    is_sale: true,
    is_featured: false,
    sale_price: 3325,
  },
  {
    id: 3,
    name: "Running Shoes",
    price: 4500,
    image: "https://example.com/runningshoes1.jpg",
    description: "High-performance running shoes for athletes.",
    quantity: 20,
    transparent_image: true,
    sizable: true,
    colors: ["green", "yellow"],
    sizes: ["40", "41", "42", "43"],
    discount: 15,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 3825,
  },
  {
    id: 4,
    name: "Leather Boots",
    price: 5500,
    image: "https://example.com/leatherboots1.jpg",
    description: "Durable leather boots for all terrains.",
    quantity: 8,
    transparent_image: false,
    sizable: true,
    colors: ["black", "tan"],
    sizes: ["39", "41", "43"],
    discount: 20,
    is_new: false,
    is_sale: false,
    is_featured: true,
    sale_price: 4400,
  },
  {
    id: 5,
    name: "Flip Flops",
    price: 1000,
    image: "https://example.com/flipflops1.jpg",
    description: "Comfortable flip flops for casual outings.",
    quantity: 30,
    transparent_image: false,
    sizable: false,
    colors: ["blue", "white"],
    sizes: ["36", "37", "38"],
    discount: 0,
    is_new: true,
    is_sale: false,
    is_featured: false,
    sale_price: 1000,
  },
  {
    id: 6,
    name: "Formal Shoes",
    price: 5000,
    image: "https://example.com/formalshoes1.jpg",
    description: "Stylish formal shoes for professional settings.",
    quantity: 12,
    transparent_image: true,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["40", "41", "42", "44"],
    discount: 10,
    is_new: false,
    is_sale: true,
    is_featured: true,
    sale_price: 4500,
  },
  {
    id: 7,
    name: "High Heels",
    price: 3000,
    image: "https://example.com/highheels1.jpg",
    description: "Elegant high heels for special occasions.",
    quantity: 5,
    transparent_image: true,
    sizable: true,
    colors: ["red", "gold"],
    sizes: ["36", "38", "40"],
    discount: 5,
    is_new: true,
    is_sale: true,
    is_featured: false,
    sale_price: 2850,
  },
  {
    id: 8,
    name: "Ballet Flats",
    price: 2500,
    image: "https://example.com/balletflats1.jpg",
    description: "Comfortable ballet flats for daily wear.",
    quantity: 20,
    transparent_image: false,
    sizable: true,
    colors: ["pink", "black"],
    sizes: ["35", "36", "37", "38"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: true,
    sale_price: 2500,
  },
  {
    id: 9,
    name: "Hiking Boots",
    price: 6000,
    image: "https://example.com/hikingboots1.jpg",
    description: "Rugged hiking boots for outdoor adventures.",
    quantity: 10,
    transparent_image: true,
    sizable: true,
    colors: ["brown", "olive"],
    sizes: ["40", "42", "44"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 5400,
  },
  {
    id: 10,
    name: "Sandals",
    price: 2000,
    image: "https://example.com/sandals1.jpg",
    description: "Comfortable sandals for warm weather.",
    quantity: 25,
    transparent_image: false,
    sizable: true,
    colors: ["white", "brown"],
    sizes: ["37", "38", "39", "40"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: false,
    sale_price: 2000,
  },
  {
    id: 11,
    name: "Ankle Boots",
    price: 5200,
    image: "https://example.com/ankleboots1.jpg",
    description: "Fashionable ankle boots for modern style.",
    quantity: 7,
    transparent_image: true,
    sizable: true,
    colors: ["black", "grey"],
    sizes: ["38", "40", "42"],
    discount: 5,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 4940,
  },
  {
    id: 12,
    name: "Slippers",
    price: 1200,
    image: "https://example.com/slippers1.jpg",
    description: "Soft slippers for indoor comfort.",
    quantity: 50,
    transparent_image: false,
    sizable: false,
    colors: ["blue", "grey"],
    sizes: ["36", "38", "40"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: false,
    sale_price: 1200,
  },
  {
    id: 13,
    name: "Clogs",
    price: 2500,
    image: "https://example.com/clogs1.jpg",
    description: "Comfortable clogs for casual wear.",
    quantity: 15,
    transparent_image: true,
    sizable: true,
    colors: ["white", "black"],
    sizes: ["36", "38", "40"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: false,
    sale_price: 2250,
  },
  {
    id: 14,
    name: "Running Sandals",
    price: 3000,
    image: "https://example.com/runningsandals1.jpg",
    description: "Lightweight running sandals for summer.",
    quantity: 18,
    transparent_image: false,
    sizable: true,
    colors: ["black", "blue"],
    sizes: ["38", "39", "40"],
    discount: 15,
    is_new: false,
    is_sale: true,
    is_featured: true,
    sale_price: 2550,
  },
  {
    id: 15,
    name: "Dress Shoes",
    price: 5500,
    image: "https://example.com/dressshoes1.jpg",
    description: "Elegant dress shoes for formal events.",
    quantity: 10,
    transparent_image: true,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["40", "41", "42"],
    discount: 5,
    is_new: true,
    is_sale: false,
    is_featured: false,
    sale_price: 5225,
  },
  {
    id: 16,
    name: "Espadrilles",
    price: 2000,
    image: "https://example.com/espadrilles1.jpg",
    description: "Casual espadrilles for summer.",
    quantity: 22,
    transparent_image: false,
    sizable: true,
    colors: ["beige", "navy"],
    sizes: ["37", "38", "39"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: true,
    sale_price: 2000,
  },
  {
    id: 17,
    name: "Water Shoes",
    price: 2800,
    image: "https://example.com/watershoes1.jpg",
    description: "Durable water shoes for aquatic activities.",
    quantity: 12,
    transparent_image: true,
    sizable: true,
    colors: ["blue", "grey"],
    sizes: ["39", "40", "41"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: false,
    sale_price: 2520,
  },
  {
    id: 18,
    name: "Wedges",
    price: 4000,
    image: "https://example.com/wedges1.jpg",
    description: "Stylish wedges for a modern look.",
    quantity: 8,
    transparent_image: false,
    sizable: true,
    colors: ["red", "black"],
    sizes: ["36", "38", "40"],
    discount: 15,
    is_new: false,
    is_sale: true,
    is_featured: true,
    sale_price: 3400,
  },
  {
    id: 19,
    name: "Oxford Shoes",
    price: 5300,
    image: "https://example.com/oxfordshoes1.jpg",
    description: "Classic Oxford shoes for timeless style.",
    quantity: 6,
    transparent_image: true,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["40", "42", "44"],
    discount: 20,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 4240,
  },
  {
    id: 20,
    name: "Moccasins",
    price: 3700,
    image: "https://example.com/moccasins1.jpg",
    description: "Comfortable moccasins for everyday wear.",
    quantity: 14,
    transparent_image: true,
    sizable: true,
    colors: ["brown", "tan"],
    sizes: ["39", "40", "41"],
    discount: 10,
    is_new: false,
    is_sale: true,
    is_featured: false,
    sale_price: 3330,
  },
];
