export const ProductList = [
  {
    id: 1,
    name: "Sneakers for Sport",
    price: 4000,
    image: "https://placehold.co/400x600.png",
    description: "Comfortable and stylish sneakers for sport.",
    quantity: 10,
    transparent_image: true,
    sizable: true,
    colors: ["blue", "red"],
    sizes: ["32", "44", "45"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 3200,
    rating: 4.5,
    reviewCount: 15,
    longDescription: "Detailed description of Sneakers for Sport.",
    specifications: ["Material: Synthetic", "Closure: Lace-up"],
    vendor: {
      name: "Sports Store",
      location: "City, Country",
      avatar: "https://example.com/avatar1.jpg",
    },
    reviews: [
      {
        name: "User 1",
        avatar: "https://example.com/avatar1.jpg",
        rating: 4,
        comment: "Great sneakers, very comfortable.",
      },
      {
        name: "User 2",
        avatar: "https://example.com/avatar2.jpg",
        rating: 5,
        comment: "Excellent quality, worth the price.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 2,
    name: "Casual Loafers",
    price: 3500,
    image: "https://placehold.co/400x600.png",
    description: "Elegant casual loafers for everyday wear.",
    quantity: 15,
    transparent_image: false,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["38", "40", "42"],
    discount: 5,
    is_new: false,
    is_sale: true,
    is_featured: false,
    sale_price: 3325,
    rating: 4.2,
    reviewCount: 10,
    longDescription: "Detailed description of Casual Loafers.",
    specifications: ["Material: Leather", "Closure: Slip-on"],
    vendor: {
      name: "Fashion Shoes",
      location: "City, Country",
      avatar: "https://example.com/avatar2.jpg",
    },
    reviews: [
      {
        name: "User 3",
        avatar: "https://example.com/avatar3.jpg",
        rating: 4,
        comment: "Comfortable and stylish, perfect for casual wear.",
      },
      {
        name: "User 4",
        avatar: "https://example.com/avatar4.jpg",
        rating: 4.5,
        comment: "Good quality loafers, would recommend.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 3,
    name: "Running Shoes",
    price: 4500,
    image: "https://placehold.co/400x600.png",
    description: "High-performance running shoes for athletes.",
    quantity: 20,
    transparent_image: true,
    sizable: true,
    colors: ["green", "yellow"],
    sizes: ["40", "41", "42", "43"],
    discount: 15,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 3825,
    rating: 4.7,
    reviewCount: 25,
    longDescription: "Detailed description of Running Shoes.",
    specifications: ["Material: Mesh", "Closure: Lace-up"],
    vendor: {
      name: "Running Gear Shop",
      location: "City, Country",
      avatar: "https://example.com/avatar3.jpg",
    },
    reviews: [
      {
        name: "User 5",
        avatar: "https://example.com/avatar5.jpg",
        rating: 5,
        comment: "Amazing shoes, very comfortable and durable.",
      },
      {
        name: "User 6",
        avatar: "https://example.com/avatar6.jpg",
        rating: 4.5,
        comment: "Perfect for running, great support.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 4,
    name: "Leather Boots",
    price: 5500,
    image: "https://placehold.co/400x600.png",
    description: "Durable leather boots for all terrains.",
    quantity: 8,
    transparent_image: false,
    sizable: true,
    colors: ["black", "tan"],
    sizes: ["39", "41", "43"],
    discount: 20,
    is_new: false,
    is_sale: false,
    is_featured: true,
    sale_price: 4400,
    rating: 4.3,
    reviewCount: 18,
    longDescription: "Detailed description of Leather Boots.",
    specifications: ["Material: Leather", "Closure: Zipper"],
    vendor: {
      name: "Outdoor Adventures",
      location: "City, Country",
      avatar: "https://example.com/avatar4.jpg",
    },
    reviews: [
      {
        name: "User 7",
        avatar: "https://example.com/avatar7.jpg",
        rating: 4,
        comment: "Very sturdy boots, excellent for hiking.",
      },
      {
        name: "User 8",
        avatar: "https://example.com/avatar8.jpg",
        rating: 4.5,
        comment: "Quality craftsmanship, would buy again.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 5,
    name: "Flip Flops",
    price: 1000,
    image: "https://placehold.co/400x600.png",
    description: "Comfortable flip flops for casual outings.",
    quantity: 30,
    transparent_image: false,
    sizable: false,
    colors: ["blue", "white"],
    sizes: ["36", "37", "38"],
    discount: 0,
    is_new: true,
    is_sale: false,
    is_featured: false,
    sale_price: 1000,
    rating: 4.0,
    reviewCount: 8,
    longDescription: "Detailed description of Flip Flops.",
    specifications: ["Material: Rubber", "Closure: Slip-on"],
    vendor: {
      name: "Beach Comfort",
      location: "City, Country",
      avatar: "https://example.com/avatar5.jpg",
    },
    reviews: [
      {
        name: "User 9",
        avatar: "https://example.com/avatar9.jpg",
        rating: 4,
        comment: "Good quality flip flops, comfortable for beach walks.",
      },
      {
        name: "User 10",
        avatar: "https://example.com/avatar10.jpg",
        rating: 4.5,
        comment: "Nice design, fits well.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 6,
    name: "Formal Shoes",
    price: 5000,
    image: "https://placehold.co/400x600.png",
    description: "Stylish formal shoes for professional settings.",
    quantity: 12,
    transparent_image: true,
    sizable: true,
    colors: ["black", "brown"],
    sizes: ["40", "41", "42", "44"],
    discount: 10,
    is_new: false,
    is_sale: true,
    is_featured: true,
    sale_price: 4500,
    rating: 4.4,
    reviewCount: 14,
    longDescription: "Detailed description of Formal Shoes.",
    specifications: ["Material: Leather", "Closure: Lace-up"],
    vendor: {
      name: "Elegant Style Boutique",
      location: "City, Country",
      avatar: "https://example.com/avatar6.jpg",
    },
    reviews: [
      {
        name: "User 11",
        avatar: "https://example.com/avatar11.jpg",
        rating: 4.5,
        comment: "Perfect for office wear, very comfortable.",
      },
      {
        name: "User 12",
        avatar: "https://example.com/avatar12.jpg",
        rating: 4.3,
        comment: "Excellent quality, stylish design.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 7,
    name: "High Heels",
    price: 3000,
    image: "https://placehold.co/400x600.png",
    description: "Elegant high heels for special occasions.",
    quantity: 5,
    transparent_image: true,
    sizable: true,
    colors: ["red", "gold"],
    sizes: ["36", "38", "40"],
    discount: 5,
    is_new: true,
    is_sale: true,
    is_featured: false,
    sale_price: 2850,
    rating: 4.1,
    reviewCount: 6,
    longDescription: "Detailed description of High Heels.",
    specifications: ["Material: Synthetic", "Closure: Buckle"],
    vendor: {
      name: "Evening Glamour",
      location: "City, Country",
      avatar: "https://example.com/avatar7.jpg",
    },
    reviews: [
      {
        name: "User 13",
        avatar: "https://example.com/avatar13.jpg",
        rating: 4,
        comment: "Beautiful heels, comfortable to wear.",
      },
      {
        name: "User 14",
        avatar: "https://example.com/avatar14.jpg",
        rating: 4.2,
        comment: "Stylish design, fits perfectly.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 8,
    name: "Ballet Flats",
    price: 2500,
    image: "https://placehold.co/400x600.png",
    description: "Comfortable ballet flats for daily wear.",
    quantity: 20,
    transparent_image: false,
    sizable: true,
    colors: ["pink", "black"],
    sizes: ["35", "36", "37", "38"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: true,
    sale_price: 2500,
    rating: 4.3,
    reviewCount: 12,
    longDescription: "Detailed description of Ballet Flats.",
    specifications: ["Material: Leather", "Closure: Slip-on"],
    vendor: {
      name: "Casual Comfort",
      location: "City, Country",
      avatar: "https://example.com/avatar8.jpg",
    },
    reviews: [
      {
        name: "User 15",
        avatar: "https://example.com/avatar15.jpg",
        rating: 4.5,
        comment: "Very comfortable flats, great for daily use.",
      },
      {
        name: "User 16",
        avatar: "https://example.com/avatar16.jpg",
        rating: 4,
        comment: "Nice color options, good quality.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 9,
    name: "Hiking Boots",
    price: 6000,
    image: "https://placehold.co/400x600.png",
    description: "Rugged hiking boots for outdoor adventures.",
    quantity: 10,
    transparent_image: true,
    sizable: true,
    colors: ["brown", "olive"],
    sizes: ["40", "42", "44"],
    discount: 10,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 5400,
    rating: 4.8,
    reviewCount: 30,
    longDescription: "Detailed description of Hiking Boots.",
    specifications: ["Material: Leather", "Closure: Lace-up"],
    vendor: {
      name: "Adventure Gear",
      location: "City, Country",
      avatar: "https://example.com/avatar9.jpg",
    },
    reviews: [
      {
        name: "User 17",
        avatar: "https://example.com/avatar17.jpg",
        rating: 5,
        comment: "Excellent boots, very sturdy and comfortable.",
      },
      {
        name: "User 18",
        avatar: "https://example.com/avatar18.jpg",
        rating: 4.5,
        comment: "Perfect for hiking, waterproof and durable.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 10,
    name: "Sandals",
    price: 2000,
    image: "https://placehold.co/400x600.png",
    description: "Comfortable sandals for warm weather.",
    quantity: 25,
    transparent_image: false,
    sizable: true,
    colors: ["white", "brown"],
    sizes: ["37", "38", "39", "40"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: false,
    sale_price: 2000,
    rating: 4.2,
    reviewCount: 9,
    longDescription: "Detailed description of Sandals.",
    specifications: ["Material: Synthetic", "Closure: Buckle"],
    vendor: {
      name: "Summer Comfort",
      location: "City, Country",
      avatar: "https://example.com/avatar10.jpg",
    },
    reviews: [
      {
        name: "User 19",
        avatar: "https://example.com/avatar19.jpg",
        rating: 4,
        comment: "Nice sandals, comfortable and good quality.",
      },
      {
        name: "User 20",
        avatar: "https://example.com/avatar20.jpg",
        rating: 4.5,
        comment: "Perfect for casual wear, fits well.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 11,
    name: "Ankle Boots",
    price: 5200,
    image: "https://placehold.co/400x600.png",
    description: "Fashionable ankle boots for modern style.",
    quantity: 7,
    transparent_image: true,
    sizable: true,
    colors: ["black", "grey"],
    sizes: ["38", "40", "42"],
    discount: 5,
    is_new: true,
    is_sale: true,
    is_featured: true,
    sale_price: 4940,
    rating: 4.6,
    reviewCount: 16,
    longDescription: "Detailed description of Ankle Boots.",
    specifications: ["Material: Leather", "Closure: Zipper"],
    vendor: {
      name: "Fashion Trend",
      location: "City, Country",
      avatar: "https://example.com/avatar11.jpg",
    },
    reviews: [
      {
        name: "User 21",
        avatar: "https://example.com/avatar21.jpg",
        rating: 4.5,
        comment: "Love these boots, stylish and comfortable.",
      },
      {
        name: "User 22",
        avatar: "https://example.com/avatar22.jpg",
        rating: 4.7,
        comment: "Great fit, perfect for everyday wear.",
      },
    ],
    rating: 2.2,
    reviewCount: 223,
    ratingDistribution: {
      5: 23,
      4: 12,
      3: 10,
      2: 3,
      1: 2,
    },
  },
  {
    id: 12,
    name: "Slippers",
    price: 1200,
    image: "https://placehold.co/400x600.png",
    description: "Soft slippers for indoor comfort.",
    quantity: 50,
    transparent_image: false,
    sizable: false,
    colors: ["blue", "grey"],
    sizes: ["36", "38", "40"],
    discount: 0,
    is_new: false,
    is_sale: false,
    is_featured: false,
    sale_price: 1200,
    rating: 4.0,
    reviewCount: 5,
    longDescription: "Detailed description of Slippers.",
    specifications: ["Material: Cotton", "Closure: Slip-on"],
    vendor: {
      name: "Home Comfort",
      location: "City, Country",
      avatar: "https://example.com/avatar12.jpg",
    },
    reviews: [
      {
        name: "User 23",
        avatar: "https://example.com/avatar23.jpg",
        rating: 4,
        comment: "Very cozy slippers, great for indoor use.",
      },
      {
        name: "User 24",
        avatar: "https://example.com/avatar24.jpg",
        rating: 4.5,
        comment: "Soft and comfortable, good quality.",
      },
    ],
    rating: 4.2,
    reviewCount: 253,
    ratingDistribution: {
      5: 60,
      4: 25,
      3: 10,
      2: 3,
      1: 2,
    },
  },
];
